# See https://dart.dev/guides/language/analysis-options
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true

linter:
  rules:
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - cascade_invocations
    - collection_methods_unrelated_type
    - combinators_ordering
    - comment_references
    - dangling_library_doc_comments
    - implicit_call_tearoffs
    - join_return_with_assignment
    - library_annotations
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - package_api_docs
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - prefer_final_locals
    - prefer_relative_imports
    - sort_child_properties_last
    - test_types_in_equals
    - unnecessary_library_directive
    - unreachable_from_main
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    - use_string_buffers
    - use_string_in_part_of_directives
    - use_super_parameters
