name: _json_serial_shared_test
publish_to: none
environment:
  sdk: ^3.5.0-259.0.dev

resolution: workspace

dependencies:
  stack_trace: ^1.10.0
  test: ^1.6.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
