# See https://github.com/google/mono_repo.dart for details on this file
stages:
- analyzer_and_format:
  - group:
    - format
    - analyze: --fatal-infos .
    sdk: dev
  - group:
    - analyze
    sdk: pubspec
