# See https://github.com/dart-lang/mono_repo for details

dart:
- stable

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings --fatal-infos .
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings .
