/// Parse Duration string generated by Duration.toString()
Duration $parseDuration(String duration) {
  final split = duration.split('.');
  final hms = split[0].split(':').map((v) => int.tryParse(v) ?? 0).toList();
  final micro = int.tryParse(split[1]) ?? 0;

  return Duration(
    hours: hms[0],
    minutes: hms[1],
    seconds: hms[2],
    microseconds: micro,
  );
}
