# See https://github.com/google/mono_repo.dart for details on this file
dart:
- 2.13.4

stages:
- analyzer_and_format:
  - group:
    - format
    - analyze: --fatal-warnings --fatal-infos .
    dart: [2.13.4]
- unit_test:
  - test
- ensure_build:
  - test: --run-skipped -t presubmit-only test/ensure_build_test.dart

cache:
  directories:
  - .dart_tool
