# See https://github.com/google/mono_repo.dart for details on this file
dart:
- 2.12.0
- dev

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos .

- unit_test:
  - test
- ensure_build:
  - test: --run-skipped -t presubmit-only test/ensure_build_test.dart
