name: Autosubmit

on:
  pull_request_target:
    types: [labeled]

permissions: {}

jobs:
  autosubmit:
    if: github.event.label.name == 'autosubmit'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable Auto-Merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
