# A CI configuration to auto-publish pub packages.

name: Publish

on:
  pull_request:
    branches: [ master ]
  push:
    tags: [ '[A-z]+-v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  publish:
    if: ${{ github.repository_owner == 'google' }}
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    permissions:
      id-token: write # Required for authentication using OIDC
      pull-requests: write # Required for writing the pull request note
